<a href="https://colab.research.google.com/github/JunYoung07/Python_AI_Project/blob/main/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. `Numpy`
* python은 **opensource기반** 프로그래밍 언어
* 수학, 과학 계산용 package
* `ndarray` 자료구조 활용
    * 파이썬의 `list`보다 훨씬 빠름
    * 파이썬의 `list`보다 적은 메모리 사용

In [1]:
# ! - 터미널 명령어 사용
# numpy package install
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
# numpy package import
import numpy as np
np  # np 객체의 위치 

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

### 1-1. Array(배열)

In [10]:
# python list
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1); print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [5]:
# numpy ndarray
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [9]:
# convert list into ndarray
arr1 = np.array(list2)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1-2. Array의 데이터 타입

* `ndarray`는 `list`와 다르게 배열 안에 한 개의 데이터 타입만 존재한다.

In [11]:
# data type of numpy array
arr = np.array([1, 2, 3, 4])
type(arr)

numpy.ndarray

In [14]:
# list vs. ndarray
list1 = [1, 3.14, 'Python', True]
arr1 = np.array([1, 3.14, 'Python', True])

In [16]:
print(list1)
print(arr1)

[1, 3.14, 'Python', True]
['1' '3.14' 'Python' 'True']


> `ndarray`의 데이터가 모두 `string`으로 변함. (자료형이 큰 순서로 변환)  

* 자료형의 순서: 
    * `string` > `float` > `int` > `boolean`

In [17]:
# you can change datatype
arr2 = np.array([1, 2, 3.14, 4], dtype=int)
arr2

array([1, 2, 3, 4])

In [19]:
# string -> int: only string.isdigit() == True
arr4 = np.array([1, 2, 3.14, True, '1234'], dtype=int)
arr4

array([   1,    2,    3,    1, 1234])

### 1-3. 인덱싱(Indexing)과 슬라이싱(Slicing)

In [22]:
# Basically equal to list methods
arr1 = np.array([1, 2, 3, 4, 5])
arr1.shape   # array's shape (1-D, 2-D, ...)

(5,)

In [24]:
# Indexing
print(arr1[0])
print(arr1[-1])
print(arr1[4])

1
5
5


In [25]:
# Slicing
print(arr1[0:3])
print(arr1[2:])
print(arr1[:3])

[1 2 3]
[3 4 5]
[1 2 3]


In [31]:
# 2-D array
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
arr2d.shape

(3, 4)

In [33]:
# 2-D array indexing
print(arr2d[0, 2])
print(arr2d[2, 1])

3
10


In [34]:
# view row
print(arr2d[0])
print(arr2d[0,])
print(arr2d[0, :])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [36]:
# view column
print(arr2d[:, 0])

[1 5 9]


### 1-4. Fancy 인덱싱

In [37]:
# select specific keys
arr1 = np.array([10, 23, 2, 6, 90, 85, 32, 66, 80])
idx = [1, 4, 6]
arr1[idx]

array([23, 90, 32])

In [41]:
# 2-D Array
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
arr2d[[0, 2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

### 1-5. Boolean 인덱싱

In [42]:
arr1 = np.array([1, 2, 3, 4, 5])
selValue = [True, False, False, True, False]    # must equal length 
arr1[selValue]

array([1, 4])

In [46]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
arr2d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [47]:
arr2d < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [48]:
arr2d[arr2d > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

# 2. 행렬 연산

### 2-1. 연산자
* `shape`가 같아야 함
* 같은 position끼리 연산

In [49]:
# sum
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [50]:
# subtract
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [51]:
# multiple (not a dot product)
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [52]:
# divergence
a / b

array([[0.33333333, 0.5       , 0.6       ],
       [2.        , 1.5       , 1.33333333]])

In [57]:
# dot product
a = np.array([[1, 2, 3], 
             [1, 2, 3],
             [2, 3, 4]])
b = np.array([[1, 2],
             [3, 4],
             [5, 6]])
print(a.shape, b.shape)
print()

# calc 
print(a.dot(b))
print(np.dot(a, b))

(3, 3) (3, 2)

[[22 28]
 [22 28]
 [31 40]]
[[22 28]
 [22 28]
 [31 40]]


In [67]:
# single operation
print(a + 3)
print(a - 3)
print(a * 3)
print(a / 3)

[[4 5 6]
 [4 5 6]
 [5 6 7]]
[[-2 -1  0]
 [-2 -1  0]
 [-1  0  1]]
[[ 3  6  9]
 [ 3  6  9]
 [ 6  9 12]]
[[0.33333333 0.66666667 1.        ]
 [0.33333333 0.66666667 1.        ]
 [0.66666667 1.         1.33333333]]


2-2. `arange`
* 순차적인 값 생성

In [58]:
arr1 = range(1, 11) # python standard function
arr1

range(1, 11)

In [59]:
arr2 = np.arange(1, 11) # numpy built-in function
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2-3. 정렬(`sort`)

In [60]:
arr1 = np.array([1, 10, 5, 7, 2, 4, 3, 6, 8, 9])
arr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [62]:
# ascending
np.sort(arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# descending
np.sort(arr1)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [64]:
# 정렬 상태를 유지하지 않음
arr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [65]:
result = np.sort(arr1)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# 2-D Array sort
arr2d = np.array([[11, 10, 12, 9],
                  [3, 1, 4, 2],
                  [5, 6, 7, 8]])
arr2d.shape

(3, 4)

In [69]:
# sort by axis
# axis=0: row
# axis=1: column
np.sort(arr2d, axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [70]:
np.sort(arr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [71]:
# sort by final axis
np.sort(arr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])